### PR TITLE
Fix for rogeriopradoj/vagrant-ip-show#2

### PR DESCRIPTION
**Pull request by mightydok**
Now all works fine, just add support for CLI argv.

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
Hey, looks awesome!!! I'll test a little and merging as soon as possible, ok?

Thanks in advance!

**Comment by mightydok** [comment]
Hey, no problem.
I think add option --all, or -a for list IP for all VM in multivm environment. If u agree.

**Comment by mightydok** [comment]
UP

**Comment by rogeriopradoj** [comment]
Hi, @mightydok , thanks a lot!

It's already published as v0.0.3.

About your suggestion, --all is interesting. Please go ahead!

Cheers,

Rogerio

**Pull request merged**
